on:
  schedule:
    - cron:  '15 * * * *'
  workflow_dispatch: {}

name: Mine CF Marketing Site
jobs:
  runner:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - name: Restore NPM cache
        uses: actions/cache@v3
        continue-on-error: true
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('scripts/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Mine marketing site
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          cd scripts
          npm ci
          npm run mine:marketing
        env:
          DISCORD_WEBHOOK_MARKETING: ${{ secrets.DISCORD_WEBHOOK_MARKETING }}
